# Generated by Django 4.0.1 on 2023-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
